import fs from 'fs'

const translationsMap = {
  hi: {
    totalNetDisbursed: 'कुल शुद्ध संवितरण',
    directBankUpi: 'सीधे बैंक / यूपीआई',
    completedServiceTasks: 'पूर्ण सेवा कार्य',
    jobsCount: 'कार्य',
    rating: 'रेटिंग',
    reviews: 'समीक्षाएं',
    cooperativeRetention: 'सहकारी अवधारण',
    statutoryMax: '5% वैधानिक अधिकतम',
    statutoryHourlyFloor: 'वैधानिक न्यूनतम प्रति घंटा दर',
    perHour: '/घंटा',
    verifiedMember: 'सत्यापित सदस्य',
    netPayoutVelocity: 'शुद्ध भुगतान और उचित वेतन गति',
    netPayoutSub: 'सकल बिलिंग बनाम 100% प्रत्यक्ष टेक-होम वेतन का पारदर्शी विवरण',
    bar: '📊 बार',
    line: '📈 रेखा',
    area: '🌊 क्षेत्र',
    stacked: '⚡ स्टैक्ड',
    last7Days: '📅 पिछले 7 दिन (दैनिक)',
    last4Weeks: '📅 इस महीने (साप्ताहिक)',
    noEarningsTitle: 'अभी तक कोई कमाई नहीं',
    noEarningsSub: 'जैसे ही आप सेवाओं को स्वीकार और पूरा करेंगे, आपकी दैनिक कमाई और वैधानिक 5% सहकारी शुल्क यहाँ दिखाई देंगे।',
    viewOpenJobs: 'खुले कार्य अनुरोध देखें →',
    grossCustomerTariff: 'ग्राहक सकल शुल्क',
    netWorkerPayout: 'श्रमिक शुद्ध भुगतान (95%)',
    coopRetentionDeduction: 'सहकारी 5% + कल्याण कोष',
    grossBilled: 'सकल बिल',
    netTakeHome: 'शुद्ध टेक-होम',
    currentJobQueue: 'वर्तमान कार्य कतार',
    manageAll: 'सभी प्रबंधित करें →',
    readyForAssignments: 'नए कार्यों के लिए तैयार',
    geoMatchingActive: 'एआई भौगोलिक मिलान सक्रिय है।',
    skillUpskilling: 'कौशल उन्नयन और प्रशिक्षण',
    courses: 'पाठ्यक्रम →',
    safetyProtocolAcademy: 'सुरक्षा और प्रोटोकॉल अकादमी',
    done: 'पूर्ण',
    badgesEarned: '🏆 2 बैज अर्जित',
    matchPriority: '+15% आवंटन प्राथमिकता',
    pmsbyWelfareActive: 'PMSBY कल्याण योजना सक्रिय 🛡️',
    mainMenu: 'मुख्य मेनू',
    rapidResponse: 'त्वरित आपातकालीन सहायता',
    raiseComplaint: 'शिकायत दर्ज करें',
    learningUpskilling: 'कौशल उन्नयन और प्रशिक्षण',
    zonalDashboard: 'जोनल डैशबोर्ड',
    teamRoster: 'श्रमिक रोस्टर',
    financialReports: 'वित्तीय रिपोर्ट',
    adjudicationQueue: 'निर्णय कतार',
    disputeRegistry: 'विवाद रजिस्ट्री',
    managerPortal: 'जोनल प्रबंधक परिचालन केंद्र',
    officerPortal: 'श्रम विभाग न्यायनिर्णयन पोर्टल',
    cooperativeWelfare: 'सहकारी कल्याण',
    welfareCardSub: 'सामाजिक सुरक्षा निधि कवरेज के साथ 100% उचित वेतन।',
    viewProtectionPlan: 'सुरक्षा योजना देखें',
    emergencySosButton: '30-मिनट आपातकालीन एसओएस',
    greetingMorning: 'शुभ प्रभात',
    greetingAfternoon: 'शुभ दोपहर',
    greetingEvening: 'शुभ संध्या',
    member: 'सदस्य',
    workerRole: 'श्रमिक',
    customerRole: 'ग्राहक',
    adminRole: 'सहकारी प्रशासक',
    managerRole: 'जोनल प्रबंधक',
    officerRole: 'श्रम अधिकारी',
    raiseAComplaint: 'शिकायत दर्ज करें',
    myComplaints: 'मेरी शिकायतें',
    complaintType: 'शिकायत का प्रकार',
    nonPayment: 'वेतन न मिलना / कम भुगतान',
    unsafeSite: 'असुरक्षित कार्य स्थल',
    customerDispute: 'ग्राहक विवाद',
    harassment: 'उत्पीड़न या दुर्व्यवहार',
    otherComplaint: 'अन्य समस्या',
    relatedJobId: 'संबंधित कार्य (वैकल्पिक)',
    noSpecificJob: 'कोई विशेष कार्य नहीं / सामान्य',
    detailedDescription: 'विस्तृत विवरण',
    descriptionPlaceholder: 'घटना का विवरण तारीखों और तथ्यों के साथ लिखें...',
    supportingDocs: 'साक्ष्य दस्तावेज / फोटो',
    uploadProof: 'प्रमाण अपलोड करें',
    submittingComplaint: 'शिकायत दर्ज की जा रही है...',
    submitComplaintBtn: 'श्रम अधिकारी को शिकायत प्रस्तुत करें',
    dateRaised: 'दर्ज करने की तिथि',
    viewInvestigation: 'जांच विवरण देखें →',
    noComplaintsFound: 'कोई शिकायत दर्ज नहीं की गई है',
    statusSubmitted: 'प्रस्तुत',
    statusUnderReview: 'समीक्षाधीन',
    statusInProgress: 'प्रगति पर',
    statusResolved: 'हल किया गया',
    statusRejected: 'अस्वीकृत',
    statusClosed: 'बंद',
    officialRulingNotes: 'अधिकारी के जांच नोट्स',
    rulingPending: 'श्रम कल्याण अधिकारी की समीक्षा लंबित है।',
    closeModal: 'बंद करें',
    overallProgress: 'कुल प्रगति',
    earnedBadges: 'अर्जित बैज',
    completedBadge: '✓ प्रमाणित',
    approxDuration: 'अवधि',
    moduleLessons: 'पाठ',
    startLearning: 'सीखना शुरू करें →',
    continueLearning: 'जारी रखें →',
    notStarted: 'शुरू नहीं हुआ',
    completeLessonBtn: 'पाठ पूर्ण चिह्नित करें',
    unlockCertificate: 'प्रमाणपत्र प्राप्त करें 🏆',
    congratsBadgeUnlocked: 'बधाई! नया कौशल बैज अनलॉक हुआ!',
    badgeUnlockedDesc: 'यह आधिकारिक प्रमाणन बैज आपकी प्रोफ़ाइल में जुड़ गया है और कार्य प्राथमिकता बढ़ाता है।',
  },
  mr: {
    totalNetDisbursed: 'एकूण निव्वळ वाटप',
    directBankUpi: 'थेट बँक / UPI द्वारे',
    completedServiceTasks: 'पूर्ण झालेली सेवा कामे',
    jobsCount: 'कामे',
    rating: 'रेटिंग',
    reviews: 'पुनरावलोकने',
    cooperativeRetention: 'सहकारी संस्था कपात',
    statutoryMax: '5% कायदेशीर कमाल',
    statutoryHourlyFloor: 'कायदेशीर किमान तास दर',
    perHour: '/तास',
    verifiedMember: 'सत्यापित सदस्य',
    netPayoutVelocity: 'निव्वळ वेतन आणि योग्य वेतन गती',
    netPayoutSub: 'एकूण बिलिंग विरुद्ध १००% थेट टेक-होम वेतनाचा तपशील',
    bar: '📊 बार',
    line: '📈 रेषा',
    area: '🌊 क्षेत्र',
    stacked: '⚡ स्टॅक केलेले',
    last7Days: '📅 मागील ७ दिवस (दैनिक)',
    last4Weeks: '📅 या महिन्यात (साप्ताहिक)',
    noEarningsTitle: 'अद्याप कोणतीही कमाई नाही',
    noEarningsSub: 'तुम्ही सेवा स्वीकारून पूर्ण केल्यावर तुमची कमाई येथे दिसेल.',
    viewOpenJobs: 'उपलब्ध कामे पहा →',
    grossCustomerTariff: 'ग्राहक एकूण शुल्क',
    netWorkerPayout: 'कामगार निव्वळ वेतन (९५%)',
    coopRetentionDeduction: 'सहकारी ५% + कल्याण निधी',
    grossBilled: 'एकूण बिल',
    netTakeHome: 'निव्वळ उत्पन्न',
    currentJobQueue: 'सध्याची कामांची रांग',
    manageAll: 'सर्व व्यवस्थापित करा →',
    readyForAssignments: 'कामासाठी तयार',
    geoMatchingActive: 'भौगोलिक मिलान सक्रिय आहे.',
    skillUpskilling: 'कौशल्य विकास आणि प्रशिक्षण',
    courses: 'अभ्यासक्रम →',
    safetyProtocolAcademy: 'सुरक्षा आणि प्रोटोकॉल अकादमी',
    done: 'पूर्ण',
    badgesEarned: '🏆 २ बॅज मिळवले',
    matchPriority: '+१५% प्राधान्य',
    pmsbyWelfareActive: 'PMSBY कल्याण योजना सक्रिय 🛡️',
    mainMenu: 'मुख्य मेनू',
    rapidResponse: 'जलद आपत्कालीन मदत',
    raiseComplaint: 'तक्रार दाखल करा',
    learningUpskilling: 'कौशल्य विकास आणि प्रशिक्षण',
    zonalDashboard: 'विभागीय डॅशबोर्ड',
    teamRoster: 'कामगार यादी',
    financialReports: 'आर्थिक अहवाल',
    adjudicationQueue: 'निर्णय रांग',
    disputeRegistry: 'तक्रार नोंदवही',
    managerPortal: 'विभागीय व्यवस्थापक केंद्र',
    officerPortal: 'कामगार विभाग न्यायाधिकरण पोर्टल',
    cooperativeWelfare: 'सहकारी कल्याण',
    welfareCardSub: 'सामाजिक सुरक्षा निधी संरक्षणासह १००% योग्य वेतन.',
    viewProtectionPlan: 'सुरक्षा योजना पहा',
    emergencySosButton: '३०-मिनिट आपत्कालीन मदत',
    greetingMorning: 'शुभ सकाळ',
    greetingAfternoon: 'शुभ दुपार',
    greetingEvening: 'शुभ संध्याकाळ',
    member: 'सदस्य',
    workerRole: 'कामगार',
    customerRole: 'ग्राहक',
    adminRole: 'सहकारी प्रशासक',
    managerRole: 'विभागीय व्यवस्थापक',
    officerRole: 'कामगार अधिकारी',
    raiseAComplaint: 'तक्रार दाखल करा',
    myComplaints: 'माझ्या तक्रारी',
    complaintType: 'तक्रारीचा प्रकार',
    nonPayment: 'वेतन न मिळणे / कमी मिळणे',
    unsafeSite: 'असुरक्षित कामाची जागा',
    customerDispute: 'ग्राहक वाद',
    harassment: 'छळवणूक किंवा गैरवर्तन',
    otherComplaint: 'इतर समस्या',
    relatedJobId: 'संबंधित काम (पर्यायी)',
    noSpecificJob: 'कोणतेही विशिष्ट काम नाही',
    detailedDescription: 'सविस्तर माहिती',
    descriptionPlaceholder: 'घडलेल्या घटनेची माहिती द्या...',
    supportingDocs: 'पुरावा कागदपत्रे / फोटो',
    uploadProof: 'पुरावा अपलोड करा',
    submittingComplaint: 'तक्रार दाखल केली जात आहे...',
    submitComplaintBtn: 'कामगार अधिकाऱ्याकडे तक्रार पाठवा',
    dateRaised: 'नोंदणी तारीख',
    viewInvestigation: 'तपासणी तपशील पहा →',
    noComplaintsFound: 'कोणतीही तक्रार दाखल केलेली नाही',
    statusSubmitted: 'दाखल केले',
    statusUnderReview: 'पुनरावलोकनाखाली',
    statusInProgress: 'प्रगतीपथावर',
    statusResolved: 'निवारण झाले',
    statusRejected: 'नाकारले',
    statusClosed: 'बंद',
    officialRulingNotes: 'अधिकाऱ्याच्या नोंदी',
    rulingPending: 'कामगार कल्याण अधिकाऱ्याचा निर्णय प्रलंबित आहे.',
    closeModal: 'बंद करा',
    overallProgress: 'एकूण प्रगती',
    earnedBadges: 'मिळवलेले बॅज',
    completedBadge: '✓ प्रमाणित',
    approxDuration: 'कालावधी',
    moduleLessons: 'धडे',
    startLearning: 'शिकण्यास सुरुवात करा →',
    continueLearning: 'पुढे सुरू ठेवा →',
    notStarted: 'सुरू झाले नाही',
    completeLessonBtn: 'धडा पूर्ण झाल्याची नोंद करा',
    unlockCertificate: 'प्रमाणपत्र मिळवा 🏆',
    congratsBadgeUnlocked: 'अभिनंदन! नवीन कौशल्य बॅज अनलॉक झाला!',
    badgeUnlockedDesc: 'हे अधिकृत प्रमाणपत्र बॅज तुमच्या प्रोफाइलमध्ये जोडले गेले आहे.',
  },
  te: {
    totalNetDisbursed: 'మొత్తం నికర చెల్లింపు',
    directBankUpi: 'బ్యాంక్ / UPI ద్వారా నేరుగా',
    completedServiceTasks: 'పూర్తయిన సేవా పనులు',
    jobsCount: 'పనులు',
    rating: 'రేటింగ్',
    reviews: 'సమీక్షలు',
    cooperativeRetention: 'సహకార సంస్థ రుసుము',
    statutoryMax: '5% గరిష్ట పరిమితి',
    statutoryHourlyFloor: 'కనిష్ట గంట వేతనం',
    perHour: '/గంటకు',
    verifiedMember: 'ధృవీకరించబడిన సభ్యుడు',
    netPayoutVelocity: 'నికర వేతనం & న్యాయమైన వేతన వివరాలు',
    netPayoutSub: 'మొత్తం బిల్లింగ్ మరియు 100% ప్రత్యక్ష వేతన వివరాలు',
    bar: '📊 బార్',
    line: '📈 లైన్',
    area: '🌊 ఏరియా',
    stacked: '⚡ స్టాక్డ్',
    last7Days: '📅 గత 7 రోజులు (రోజువారీ)',
    last4Weeks: '📅 ఈ నెల (వారపు)',
    noEarningsTitle: 'ఇంకా ఎలాంటి ఆదాయం నమోదు కాలేదు',
    noEarningsSub: 'మీరు పనులను పూర్తి చేసిన తర్వాత మీ సంపాదన ఇక్కడ కనిపిస్తుంది.',
    viewOpenJobs: 'అందుబాటులో ఉన్న పనులను చూడండి →',
    grossCustomerTariff: 'కస్టమర్ మొత్తం ఛార్జీ',
    netWorkerPayout: 'కార్మికుడి నికర వేతనం (95%)',
    coopRetentionDeduction: 'సహకార 5% + సంక్షేమ నిధి',
    grossBilled: 'మొత్తం బిల్లు',
    netTakeHome: 'నికర ఆదాయం',
    currentJobQueue: 'ప్రస్తుత పనుల జాబితా',
    manageAll: 'అన్నింటినీ నిర్వహించండి →',
    readyForAssignments: 'పనులకు సిద్ధంగా ఉంది',
    geoMatchingActive: 'జియో-మ్యాచింగ్ ఇంజిన్ సక్రియంగా ఉంది.',
    skillUpskilling: 'నైపుణ్యాభివృద్ధి & శిక్షణ',
    courses: 'కోర్సులు →',
    safetyProtocolAcademy: 'భద్రతా & నియమావళి అకాడమీ',
    done: 'పూర్తయింది',
    badgesEarned: '🏆 2 బ్యాడ్జీలు పొందారు',
    matchPriority: '+15% పని ప్రాధాన్యత',
    pmsbyWelfareActive: 'PMSBY సంక్షేమ పథకం సక్రియంగా ఉంది 🛡️',
    mainMenu: 'ప్రధాన మెనూ',
    rapidResponse: 'అత్యవసర సహాయం',
    raiseComplaint: 'ఫిర్యాదు చేయండి',
    learningUpskilling: 'నైపుణ్యాభివృద్ధి & శిక్షణ',
    zonalDashboard: 'జోనల్ డాష్‌బోర్డ్',
    teamRoster: 'కార్మికుల జాబితా',
    financialReports: 'ఆర్థిక నివేదికలు',
    adjudicationQueue: 'తీర్పు వరుస',
    disputeRegistry: 'వివాదాల రిజిస్ట్రీ',
    managerPortal: 'జోనల్ మేనేజర్ కేంద్రం',
    officerPortal: 'కార్మిక శాఖ మధ్యవర్తిత్వ పోర్టల్',
    cooperativeWelfare: 'సహకార సంక్షేమం',
    welfareCardSub: 'సామాజిక భద్రతా నిధితో 100% న్యాయమైన వేతనాలు.',
    viewProtectionPlan: 'రక్షణ ప్రణాళికను చూడండి',
    emergencySosButton: '30-నిమిషాల అత్యవసర SOS',
    greetingMorning: 'శుభోదయం',
    greetingAfternoon: 'శుభ మధ్యాహ్నం',
    greetingEvening: 'శుభ సాయంత్రం',
    member: 'సభ్యుడు',
    workerRole: 'కార్మికుడు',
    customerRole: 'కస్టమర్',
    adminRole: 'సహకార అడ్మిన్',
    managerRole: 'జోనల్ మేనేజర్',
    officerRole: 'కార్మిక అధికారి',
    raiseAComplaint: 'ఫిర్యాదు నమోదు చేయండి',
    myComplaints: 'నా ఫిర్యాదులు',
    complaintType: 'ఫిర్యాదు రకం',
    nonPayment: 'వేతనం చెల్లించకపోవడం',
    unsafeSite: 'అసురక్షిత పని ప్రదేశం',
    customerDispute: 'కస్టమర్ వివాదం',
    harassment: 'వేధింపులు లేదా దుష్ప్రవర్తన',
    otherComplaint: 'ఇతర సమస్యలు',
    relatedJobId: 'సంబంధిత పని (ఐచ్ఛికం)',
    noSpecificJob: 'ప్రత్యేక పని లేదు',
    detailedDescription: 'వివరణాత్మక స్టేట్‌మెంట్',
    descriptionPlaceholder: 'సమస్యను వివరంగా రాయండి...',
    supportingDocs: 'ఆధార పత్రాలు / ఫోటోలు',
    uploadProof: 'రుజువును అప్‌లోడ్ చేయండి',
    submittingComplaint: 'ఫిర్యాదు సమర్పించబడుతోంది...',
    submitComplaintBtn: 'కార్మిక అధికారికి ఫిర్యాదు సమర్పించండి',
    dateRaised: 'నమోదు తేదీ',
    viewInvestigation: 'విచారణ వివరాలను చూడండి →',
    noComplaintsFound: 'ఎలాంటి ఫిర్యాదులు నమోదు కాలేదు',
    statusSubmitted: 'సమర్పించబడింది',
    statusUnderReview: 'సమీక్షలో ఉంది',
    statusInProgress: 'పురోగతిలో ఉంది',
    statusResolved: 'పరిష్కరించబడింది',
    statusRejected: 'తిరస్కరించబడింది',
    statusClosed: 'ముగిసింది',
    officialRulingNotes: 'అధికారి విచారణ నోట్స్',
    rulingPending: 'కార్మిక సంక్షేమ అధికారి సమీక్ష పెండింగ్‌లో ఉంది.',
    closeModal: 'మూసివేయి',
    overallProgress: 'మొత్తం పురోగతి',
    earnedBadges: 'పొందిన బ్యాడ్జీలు',
    completedBadge: '✓ సర్టిఫైడ్',
    approxDuration: 'వ్యవధి',
    moduleLessons: 'పాఠాలు',
    startLearning: 'నేర్చుకోవడం ప్రారంభించండి →',
    continueLearning: 'కొనసాగించండి →',
    notStarted: 'ప్రారంభం కాలేదు',
    completeLessonBtn: 'పాఠం పూర్తయినట్లు గుర్తించండి',
    unlockCertificate: 'సర్టిఫికేట్ పొందండి 🏆',
    congratsBadgeUnlocked: 'అభినందనలు! కొత్త నైపుణ్య బ్యాడ్జ్ అన్‌లాక్ అయింది!',
    badgeUnlockedDesc: 'ఈ అధికారిక సర్టిఫికేషన్ బ్యాడ్జ్ మీ ప్రొఫైల్‌కు జోడించబడింది.',
  },
  kn: {
    totalNetDisbursed: 'ಒಟ್ಟು ನಿವ್ವಳ ವಿತರಣೆ',
    directBankUpi: 'ನೇರ ಬ್ಯಾಂಕ್ / UPI ಮೂಲಕ',
    completedServiceTasks: 'ಪೂರ್ಣಗೊಂಡ ಸೇವಾ ಕಾರ್ಯಗಳು',
    jobsCount: 'ಕೆಲಸಗಳು',
    rating: 'ರೇಟಿಂಗ್',
    reviews: 'ವಿಮರ್ಶೆಗಳು',
    cooperativeRetention: 'ಸಹಕಾರಿ ಸಂಸ್ಥೆ ಶುಲ್ಕ',
    statutoryMax: '5% ಶಾಸನಬದ್ಧ ಗರಿಷ್ಠ',
    statutoryHourlyFloor: 'ಕನಿಷ್ಠ ಗಂಟೆಯ ವೇತನ',
    perHour: '/ಗಂಟೆಗೆ',
    verifiedMember: 'ಪರಿಶೀಲಿಸಿದ ಸದಸ್ಯ',
    netPayoutVelocity: 'ನಿವ್ವಳ ವೇತನ ಮತ್ತು ನ್ಯಾಯಯುತ ವೇತನ ವೇಗ',
    netPayoutSub: 'ಒಟ್ಟು ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು 100% ನೇರ ವೇತನದ ವಿವರ',
    bar: '📊 ಬಾರ್',
    line: '📈 ಲೈನ್',
    area: '🌊 ಏರಿಯಾ',
    stacked: '⚡ ಸ್ಟಾಕ್ಡ್',
    last7Days: '📅 ಕಳೆದ 7 ದಿನಗಳು (ದೈನಂದಿನ)',
    last4Weeks: '📅 ಈ ತಿಂಗಳು (ವಾರದ)',
    noEarningsTitle: 'ಇನ್ನೂ ಯಾವುದೇ ಗಳಿಕೆ ಇಲ್ಲ',
    noEarningsSub: 'ನೀವು ಸೇವೆಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದಾಗ ನಿಮ್ಮ ಗಳಿಕೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.',
    viewOpenJobs: 'ಲಭ್ಯವಿರುವ ಕೆಲಸಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
    grossCustomerTariff: 'ಗ್ರಾಹಕರ ಒಟ್ಟು ಶುಲ್ಕ',
    netWorkerPayout: 'ಕಾರ್ಮಿಕರ ನಿವ್ವಳ ವೇತನ (95%)',
    coopRetentionDeduction: 'ಸಹಕಾರಿ 5% + ಕಲ್ಯಾಣ ನಿಧಿ',
    grossBilled: 'ಒಟ್ಟು ಬಿಲ್',
    netTakeHome: 'ನಿವ್ವಳ ಗಳಿಕೆ',
    currentJobQueue: 'ಪ್ರಸ್ತುತ ಕೆಲಸದ ಸಾಲು',
    manageAll: 'ಎಲ್ಲವನ್ನೂ ನಿರ್ವಹಿಸಿ →',
    readyForAssignments: 'ಕೆಲಸಕ್ಕೆ ಸಿದ್ಧ',
    geoMatchingActive: 'ಜಿಯೋ-ಹೊಂದಾಣಿಕೆ ಎಂಜಿನ್ ಸಕ್ರಿಯವಾಗಿದೆ.',
    skillUpskilling: 'ಕೌಶಲ್ಯ ತರಬೇತಿ ಮತ್ತು ಅಭಿವೃದ್ಧಿ',
    courses: 'ಕೋರ್ಸ್‌ಗಳು →',
    safetyProtocolAcademy: 'ಸುರಕ್ಷತೆ ಮತ್ತು ಪ್ರೋಟೋಕಾಲ್ ಅಕಾಡೆಮಿ',
    done: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    badgesEarned: '🏆 2 ಬ್ಯಾಡ್ಜ್‌ಗಳನ್ನು ಗಳಿಸಲಾಗಿದೆ',
    matchPriority: '+15% ಕೆಲಸದ ಆದ್ಯತೆ',
    pmsbyWelfareActive: 'PMSBY ಕಲ್ಯಾಣ ಯೋಜನೆ ಸಕ್ರಿಯವಾಗಿದೆ 🛡️',
    mainMenu: 'ಮುಖ್ಯ ಮೆನು',
    rapidResponse: 'ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ',
    raiseComplaint: 'ದೂರು ದಾಖಲಿಸಿ',
    learningUpskilling: 'ಕೌಶಲ್ಯ ತರಬೇತಿ ಮತ್ತು ಅಭಿವೃದ್ಧಿ',
    zonalDashboard: 'ವಲಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    teamRoster: 'ಕಾರ್ಮಿಕರ ಪಟ್ಟಿ',
    financialReports: 'ಹಣಕಾಸು ವರದಿಗಳು',
    adjudicationQueue: 'ತೀರ್ಪು ಸಾಲು',
    disputeRegistry: 'ವಿವಾದಗಳ ನೋಂದಣಿ',
    managerPortal: 'ವಲಯ ವ್ಯವಸ್ಥಾಪಕ ಕೇಂದ್ರ',
    officerPortal: 'ಕಾರ್ಮಿಕ ಇಲಾಖೆ ನ್ಯಾಯಮಂಡಳಿ ಪೋರ್ಟಲ್',
    cooperativeWelfare: 'ಸಹಕಾರಿ ಕಲ್ಯಾಣ',
    welfareCardSub: 'ಸಾಮಾಜಿಕ ಭದ್ರತಾ ನಿಧಿಯೊಂದಿಗೆ 100% ನ್ಯಾಯಯುತ ವೇತನ.',
    viewProtectionPlan: 'ರಕ್ಷಣೆ ಯೋಜನೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    emergencySosButton: '30-ನಿಮಿಷಗಳ ತುರ್ತು SOS',
    greetingMorning: 'ಶುಭೋದಯ',
    greetingAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    greetingEvening: 'ಶುಭ ಸಂಜೆ',
    member: 'ಸದಸ್ಯ',
    workerRole: 'ಕಾರ್ಮಿಕ',
    customerRole: 'ಗ್ರಾಹಕ',
    adminRole: 'ಸಹಕಾರಿ ನಿರ್ವಾಹಕ',
    managerRole: 'ವಲಯ ವ್ಯವಸ್ಥಾಪಕ',
    officerRole: 'ಕಾರ್ಮಿಕ ಅಧಿಕಾರಿ',
    raiseAComplaint: 'ದೂರು ದಾಖಲಿಸಿ',
    myComplaints: 'ನನ್ನ ದೂರುಗಳು',
    complaintType: 'ದೂರಿನ ಪ್ರಕಾರ',
    nonPayment: 'ವೇತನ ಪಾವತಿಸದಿರುವುದು',
    unsafeSite: 'ಅಸುರಕ್ಷಿತ ಕೆಲಸದ ಸ್ಥಳ',
    customerDispute: 'ಗ್ರಾಹಕರ ವಿವಾದ',
    harassment: 'ಕಿರುಕುಳ ಅಥವಾ ದುರ್ನಡತೆ',
    otherComplaint: 'ಇತರ ಸಮಸ್ಯೆಗಳು',
    relatedJobId: 'ಸಂಬಂಧಿತ ಕೆಲಸ (ಐಚ್ಛಿಕ)',
    noSpecificJob: 'ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಕೆಲಸವಿಲ್ಲ',
    detailedDescription: 'ವಿವರವಾದ ವಿವರಣೆ',
    descriptionPlaceholder: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರವಾಗಿ ಬರೆಯಿರಿ...',
    supportingDocs: 'ದಾಖಲೆಗಳು / ಫೋಟೋಗಳು',
    uploadProof: 'ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    submittingComplaint: 'ದೂರು ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    submitComplaintBtn: 'ಕಾರ್ಮಿಕ ಅಧಿಕಾರಿಗೆ ದೂರು ಸಲ್ಲಿಸಿ',
    dateRaised: 'ದಾಖಲಿಸಿದ ದಿನಾಂಕ',
    viewInvestigation: 'ತನಿಖಾ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
    noComplaintsFound: 'ಯಾವುದೇ ದೂರುಗಳು ದಾಖಲಾಗಿಲ್ಲ',
    statusSubmitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    statusUnderReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    statusInProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    statusResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    statusRejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    statusClosed: 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
    officialRulingNotes: 'ಅಧಿಕಾರಿಯ ತನಿಖಾ ಟಿಪ್ಪಣಿಗಳು',
    rulingPending: 'ಕಾರ್ಮಿಕ ಕಲ್ಯಾಣ ಅಧಿಕಾರಿಯ ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ.',
    closeModal: 'ಮುಚ್ಚಿ',
    overallProgress: 'ಒಟ್ಟು ಪ್ರಗತಿ',
    earnedBadges: 'ಗಳಿಸಿದ ಬ್ಯಾಡ್ಜ್‌ಗಳು',
    completedBadge: '✓ ಪ್ರಮಾಣೀಕೃತ',
    approxDuration: 'ಅವಧಿ',
    moduleLessons: 'ಪಾಠಗಳು',
    startLearning: 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ →',
    continueLearning: 'ಮುಂದುವರಿಸಿ →',
    notStarted: 'ಪ್ರಾರಂಭವಾಗಿಲ್ಲ',
    completeLessonBtn: 'ಪಾಠ ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    unlockCertificate: 'ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ 🏆',
    congratsBadgeUnlocked: 'ಅಭಿನಂದನೆಗಳು! ಹೊಸ ಕೌಶಲ್ಯ ಬ್ಯಾಡ್ಜ್ ಅನ್‌ಲಾಕ್ ಆಗಿದೆ!',
    badgeUnlockedDesc: 'ಈ ಅಧಿಕೃತ ಪ್ರಮಾಣೀಕರಣ ಬ್ಯಾಡ್ಜ್ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಸೇರಿದೆ.',
  },
  bn: {
    totalNetDisbursed: 'মোট নেট বিতরণ',
    directBankUpi: 'সরাসরি ব্যাংক / UPI মাধ্যমে',
    completedServiceTasks: 'সম্পন্ন সেবামূলক কাজ',
    jobsCount: 'কাজ',
    rating: 'রেটিং',
    reviews: 'পর্যালোচনা',
    cooperativeRetention: 'সমবায় ধরে রাখা ফি',
    statutoryMax: '৫% বিধিবদ্ধ সর্বোচ্চ',
    statutoryHourlyFloor: 'বিধিবদ্ধ ন্যূনতম ঘণ্টাপ্রতি মজুরি',
    perHour: '/ঘণ্টা',
    verifiedMember: 'যাচাইকৃত সদস্য',
    netPayoutVelocity: 'নেট পেআউট এবং ন্যায্য মজুরির গতি',
    netPayoutSub: 'মোট বিলিং বনাম ১০০% সরাসরি উপার্জনের স্বচ্ছ বিবরণ',
    bar: '📊 বার',
    line: '📈 রেখা',
    area: '🌊 অঞ্চল',
    stacked: '⚡ স্ট্যাক করা',
    last7Days: '📅 গত ৭ দিন (দৈনিক)',
    last4Weeks: '📅 এই মাসে (সাপ্তাহিক)',
    noEarningsTitle: 'এখনও কোনো উপার্জন নেই',
    noEarningsSub: 'আপনি কাজ গ্রহণ এবং সম্পন্ন করলে আপনার দৈনিক উপার্জন এখানে প্রদর্শিত হবে।',
    viewOpenJobs: 'উপলব্ধ কাজের অনুরোধ দেখুন →',
    grossCustomerTariff: 'গ্রাহকের মোট চার্জ',
    netWorkerPayout: 'শ্রমিকের নেট মজুরি (৯৫%)',
    coopRetentionDeduction: 'সমবায় ৫% + কল্যাণ তহবিল',
    grossBilled: 'মোট বিল',
    netTakeHome: 'নেট আয়',
    currentJobQueue: 'বর্তমান কাজের সারি',
    manageAll: 'সব পরিচালনা করুন →',
    readyForAssignments: 'কাজের জন্য প্রস্তুত',
    geoMatchingActive: 'ভৌগোলিক ম্যাচিং ইঞ্জিন সক্রিয়।',
    skillUpskilling: 'দক্ষতা বৃদ্ধি ও প্রশিক্ষণ',
    courses: 'কোর্স →',
    safetyProtocolAcademy: 'নিরাপত্তা ও প্রোটোকল একাডেমি',
    done: 'সম্পন্ন',
    badgesEarned: '🏆 ২টি ব্যাজ অর্জিত',
    matchPriority: '+১৫% কাজের অগ্রাধিকার',
    pmsbyWelfareActive: 'PMSBY কল্যাণ প্রকল্প সক্রিয় 🛡️',
    mainMenu: 'মূল মেনু',
    rapidResponse: 'জরুরি সহায়তা',
    raiseComplaint: 'অভিযোগ দায়ের করুন',
    learningUpskilling: 'দক্ষতা বৃদ্ধি ও প্রশিক্ষণ',
    zonalDashboard: 'জোনাল ড্যাশবোর্ড',
    teamRoster: 'শ্রমিক রোস্টার',
    financialReports: 'আর্থিক প্রতিবেদন',
    adjudicationQueue: 'বিচারিক সারি',
    disputeRegistry: 'বিরোধ রেজিস্ট্রি',
    managerPortal: 'জোনাল ম্যানেজার কেন্দ্র',
    officerPortal: 'শ্রম দপ্তর ট্রাইব্যুনাল পোর্টাল',
    cooperativeWelfare: 'সমবায় কল্যাণ',
    welfareCardSub: 'সামাজিক নিরাপত্তা তহবিল সহ ১০০% ন্যায্য মজুরি।',
    viewProtectionPlan: 'সুরক্ষা পরিকল্পনা দেখুন',
    emergencySosButton: '৩০-মিনিট জরুরি SOS',
    greetingMorning: 'সুপ্রভাত',
    greetingAfternoon: 'শুভ দুপুর',
    greetingEvening: 'শুভ সন্ধ্যা',
    member: 'সদস্য',
    workerRole: 'শ্রমিক',
    customerRole: 'গ্রাহক',
    adminRole: 'সমবায় প্রশাসক',
    managerRole: 'জোনাল ম্যানেজার',
    officerRole: 'শ্রম কর্মকর্তা',
    raiseAComplaint: 'অভিযোগ দায়ের করুন',
    myComplaints: 'আমার অভিযোগসমূহ',
    complaintType: 'অভিযোগের ধরন',
    nonPayment: 'মজুরি বকেয়া / কম পেমেন্ট',
    unsafeSite: 'অনিরাপদ কর্মক্ষেত্র',
    customerDispute: 'গ্রাহকের সাথে বিরোধ',
    harassment: 'হয়রানি বা অসদাচরণ',
    otherComplaint: 'অন্যান্য সমস্যা',
    relatedJobId: 'সম্পর্কিত কাজ (ঐচ্ছিক)',
    noSpecificJob: 'নির্দিষ্ট কোনো কাজ নেই',
    detailedDescription: 'বিস্তারিত বিবরণ',
    descriptionPlaceholder: 'ঘটনাটি বিস্তারিতভাবে লিখুন...',
    supportingDocs: 'প্রমাণপত্র / ছবি',
    uploadProof: 'প্রমাণ আপলোড করুন',
    submittingComplaint: 'অভিযোগ জমা হচ্ছে...',
    submitComplaintBtn: 'শ্রম কর্মকর্তার কাছে অভিযোগ জমা দিন',
    dateRaised: 'দায়েরের তারিখ',
    viewInvestigation: 'তদন্তের বিবরণ দেখুন →',
    noComplaintsFound: 'কোনো অভিযোগ পাওয়া যায়নি',
    statusSubmitted: 'জমা হয়েছে',
    statusUnderReview: 'পর্যালোচনাধীন',
    statusInProgress: 'চলমান',
    statusResolved: 'মীমাংসিত',
    statusRejected: 'প্রত্যাখ্যাত',
    statusClosed: 'বন্ধ',
    officialRulingNotes: 'কর্মকর্তার তদন্ত নোট',
    rulingPending: 'শ্রম কল্যাণ কর্মকর্তার সিদ্ধান্ত অপেক্ষমাণ।',
    closeModal: 'বন্ধ করুন',
    overallProgress: 'সামগ্রিক অগ্রগতি',
    earnedBadges: 'অর্জিত ব্যাজ',
    completedBadge: '✓ প্রত্যয়িত',
    approxDuration: 'সময়কাল',
    moduleLessons: 'পাঠ',
    startLearning: 'শেখা শুরু করুন →',
    continueLearning: 'চালিয়ে যান →',
    notStarted: 'শুরু হয়নি',
    completeLessonBtn: 'পাঠ সম্পন্ন হয়েছে চিহ্নিত করুন',
    unlockCertificate: 'সার্টিফিকেট পান 🏆',
    congratsBadgeUnlocked: 'অভিনন্দন! নতুন দক্ষতা ব্যাজ আনলক হয়েছে!',
    badgeUnlockedDesc: 'এই অফিসিয়াল সার্টিফিকেশন ব্যাজটি আপনার প্রোফাইলে যুক্ত হয়েছে।',
  },
}

let i18nContent = fs.readFileSync('src/context/I18nContext.jsx', 'utf8')

function injectDict(content, langKey, entries) {
  const regex = new RegExp('(\\s+' + langKey + ':\\s*\\{)')
  const match = content.match(regex)
  if (!match) return content

  const startIdx = match.index + match[0].length
  const lines = Object.entries(entries)
    .map(([k, v]) => `\n    ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('')

  return content.slice(0, startIdx) + lines + content.slice(startIdx)
}

for (const [lang, dict] of Object.entries(translationsMap)) {
  i18nContent = injectDict(i18nContent, lang, dict)
}

fs.writeFileSync('src/context/I18nContext.jsx', i18nContent, 'utf8')
console.log('Successfully injected translations for hi, mr, te, kn, bn into I18nContext.jsx!')
